- name: ecs.version
  external: ecs
- name: event.kind
  external: ecs
- name: event.category
  external: ecs
- name: event.type
  external: ecs
- name: event.outcome
  external: ecs
- name: event.created
  external: ecs
- name: event.start
  external: ecs
- name: cloud.provider
  external: ecs
- name: cloud.region
  external: ecs
- name: cloud.instance.id
  external: ecs
- name: cloud.instance.name
  external: ecs
- name: user.name
  external: ecs
- name: url.full
  external: ecs
- name: labels
  external: ecs
- name: error.message
  external: ecs
- name: tags
  external: ecs
- name: related.user
  external: ecs
