services:
  ovh_object_storage_container:
    image: docker.elastic.co/observability/stream:v0.22.0
    hostname: ovh_object_storage_container
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-container.yml
