---
description: "Pipeline to parse and map queries Bind9 log lines to ECS format"
processors:
  - grok:
      field: "message"
      patterns:
        - "%{BIND9_TIMESTAMP:timestamp}.%{INT:millisecond} %{GREEDYDATA:category}: %{LOGLEVEL:log.level}: %{GREEDYDATA:event.reason} %{DATA:client.id} %{IP:client.ip}#%{NUMBER:client.port} \\(%{HOSTNAME:client.hostname}\\): query: %{HOSTNAME:dns.question.name} %{WORD:dns.question.class} %{WORD:dns.question.type} %{DATA:dns.flags} \\(%{IP:destination.ip}\\)"
  - set:
      field: "timestamp"
      value: "{{timestamp}}.{{millisecond}}Z"
      ignore_failure: true
  - date:
      field: "timestamp"
      target_field: "@timestamp"
      formats:
        - "dd-MMM-yyyy HH:mm:ss.SSS'Z'"
        - "d-MMM-yyyy HH:mm:ss.SSS'Z'"
      timezone: "UTC"
  - set:
      field: "event.category"
      value: "network"
  - set:
      field: "event.kind"
      value: "event"
  - set:
      field: "event.type"
      value: "info"
  - remove:
      field: "millisecond"

on_failure:
  - set:
      field: "error.message"
      value: "{{ _ingest.on_failure_message }}"
